### ISSUE TITLE
list of dependancies is missing "vi" (for the xxd util)

### ISSUE THREAD

**Issue by mrdudz** [sasq64/chipmachine#24]
what the topic says.... ideally xxd would be replaced by something like "hex", so you dont have to install vi just for that trivial tool.

greg has a nice small replacement here: https://github.com/gregkh/xxdi

**Comment by sasq64** [comment]
Except the replacement requires Perl :) I agree it would be nice with an exact list of dependencies but I don't think it qualifies as an issue.
