### ISSUE TITLE
displayed title/song name often doesnt update correctly

### ISSUE THREAD

**Issue by mrdudz** [sasq64/chipmachine#26]
often the info in the top left corner belongs to some tune that was played before the current one, see this screenshot:

![bug](http://hitmen.c02.at/linked/bug.png)

this happened after playing kjell nordboe composer shuffle (ctrl+4), then typing "groepaz" into the search screen and playing the aurora remix

**Comment by sasq64** [comment]
Was this with 1.0, because I thought I fixed a bug relating to this?

**Comment by mrdudz** [comment]
build fresh from git clone today. it seems to happen more often than not actually :)

**Comment by sasq64** [comment]
Think I fixed it, committed to the dev branch

**Comment by mrdudz** [comment]
apparently works now, thanx!
