### ISSUE TITLE
some UADEPLAY files crash the app

### ISSUE THREAD

**Issue by christophsturm** [sasq64/chipmachine#27]
for example this file:
"where the streets have no name.mus" produces a null pointer in do_get_mem_long

<pre>
[UADEPlugin.cpp:88] UADEPLAY /Users/christoph/.cache/chipmachine/_webfiles/http%3a%2f%2fftp.modland.com%2fpub%2fmodules%2fStereo Sidplayer%2fDC%2fwhere the streets have no name.mus
Process 8365 stopped
* thread #16: tid = 0x1a4017, 0x0000000100cd3aa4 chipmachine`do_get_mem_long(a=0x0000000000000000) + 20 at maccess.h:13, stop reason = EXC_BAD_ACCESS (code=1, address=0x0)
    frame #0: 0x0000000100cd3aa4 chipmachine`do_get_mem_long(a=0x0000000000000000) + 20 at maccess.h:13
   10  	{
   11  	    uae_u8 *b = (uae_u8 *)a;
   12  	    
-> 13  	    return (*b << 24) | (*(b+1) << 16) | (*(b+2) << 8) | (*(b+3));
</pre>

**Comment by sasq64** [comment]
Known problem, need to have a better list of supported formats for UADE.

**Comment by mldoering** [comment]
Am Fri, 20 Nov 2015 05:59:37 -0800
schrieb Jonas Minnberg <notifications@github.com>:

> Known problem, need to have a better list of supported formats for
> UADE.
> 
> ---
> Reply to this email directly or view it on GitHub:
> https://github.com/sasq64/chipmachine/issues/27#issuecomment-158409407


Hej Jonas,

if I can be of any help, just say a word. I'd be more than happy.

One of the problems with a lot of formats is the missing fileheuristic.
Uade relies on the right file prefix (file suffix is
working for many formats but replayers like tfmx think they run on an
amiga so they expect things to be like on one and not a pc)

I started to add filedetection in amifilemagic.c for some few, but it's
far from complete or fool proof, and I fix things as things fall
apart. ;-)

Another problem are buggy files, bad ripps, so if it's a fileformat that
should be supported it's also one of the reasons it could fail.

And a potential culprit could also be bad or incompatible code in the
music. (e.g. odd memory access, 68000/020/060 instructions).

nevertheless, I can try to have look at the files if you like.

ha det bra,

Michael "mld" Doering

**Comment by sasq64** [comment]
Cool.
In the last version I at least don't try to play non UADE formats which caused many crashes.
But you can maybe tell me why Startrekker songs are reported as "Audiosculpture"? :)

**Comment by mldoering** [comment]
Am Sun, 22 Nov 2015 13:36:16 -0800
schrieb Jonas Minnberg <notifications@github.com>:

> Cool.
> In the last version I at least don't try to play non UADE formats
> which caused many crashes. But you can maybe tell me why Startrekker
> songs are reported as "Audiosculpture"? :)
> 
> ---
> Reply to this email directly or view it on GitHub:
> https://github.com/sasq64/chipmachine/issues/27#issuecomment-158801469

It's because Audiosculture is the successor of Startrekker. I think
Exolon renamed his tracker and developed it further. From what I know
it should be backward compatible

**Comment by sasq64** [comment]
OK, mystery solved :)

**Comment by mldoering** [comment]
Am Mon, 23 Nov 2015 00:48:46 -0800
schrieb Jonas Minnberg <notifications@github.com>:

> OK, mystery solved :)
> 
> ---
> Reply to this email directly or view it on GitHub:
> https://github.com/sasq64/chipmachine/issues/27#issuecomment-158878431

:-) as a follow up...

if the mods have an EXO4 tag it's a mod with synth instruments, and it
is played with the special Audiosculpture replay.

Startrekker/Audiosculpture mods with the FLT4 tag are played as a normal
sample mod file (with some features enabled/disabled to make it sound
right).
