### ISSUE TITLE
distortion/clipping when playing sids

### ISSUE THREAD

**Issue by mrdudz** [sasq64/chipmachine#28]
in some (for some strange reason, really only some) sid tunes there is noticeable digital clipping/distortion ... for example the bassdrum in "multiplexing combat living" by linus.
edit: another "pot wears loon pants" by linus

if i can trust the VU meters in the pulseaudio volume thingy those tunes come in at a much(!) higher level than other tunes..... *shrug*

**Comment by sasq64** [comment]
If the same tune sounds right in Vice then it is a bug, otherwise it's just the fact that Sid emulation isn't perfect yet.

**Comment by sasq64** [comment]
If the same tune sounds right in Vice then it is a bug, otherwise it's just the fact that Sid emulation isn't perfect yet.

**Comment by mrdudz** [comment]
you are right... its the same in VICE (vsid) - should have checked myself first :)
