### ISSUE TITLE
Font looks really small in hidpi resolutions

### ISSUE THREAD

**Issue by arboreal84** [sasq64/chipmachine#29]
I use a hidpi resolution and the fonts look really small making the program hard to use.

**Comment by sasq64** [comment]
If you're feeling experimental you fiddle with the settings in 
`lua/screen.lua`
(Most settings are of the format x,y,scale,color ...)
...but better rescaling support is on my TODO.

**Comment by partycoder** [comment]
Thanks, that worked

**Comment by sasq64** [comment]
Should be better in 1.3
