### ISSUE TITLE
64bit debian install instructions 'libglfw3-dev' has no installation candidate

### ISSUE THREAD

**Issue by Gunstick** [sasq64/chipmachine#33]
on 64bit linux dependencies installation gives this:

Package libglfw3-dev is not available, but is referred to by another package.
This may mean that the package is missing, has been obsoleted, or
is only available from another source
However the following packages replace it:
  libglfw3-dev:i386

I would need to lookup how to build 32bit soft on a 64bit system. When I manage to do it I will update this ticket.

**Comment by sasq64** [comment]
You should not have to build as 32bit. Ubuntu has libglfw3-dev in 64bit, I don't know why plain Debian would not have it.
If there is no package you can download glfw and build and install manually.

**Comment by Gunstick** [comment]
Looks like my linux may be too old?
$ apt-cache search libglfw
libglfw-dev - header files and static libraries portable framework for OpenGL application development
libglfw2 - Shared libraries portable framework for OpenGL application development
$ uname -a
Linux breeze 3.11-2-amd64 #1 SMP Debian 3.11.8-1 (2013-11-13) x86_64 GNU/Linux
$ lsb_release -a
No LSB modules are available.
Distributor ID:	LinuxMint
Description:	LMDE Cinnamon Edition
Release:	1
Codename:	debian
$ cat /etc/debian_version 
jessie/sid

I guess the mint people messed it up. Going back to ubuntu may be a good idea. Mint is such a shit.

**Comment by Gunstick** [comment]
Ok, read this
http://stackoverflow.com/questions/25151085/unable-to-locate-package-glfw-on-linux-mint
done that
$ sudo apt-get install libglfw-dev libglfw2
Reading package lists... Done
Building dependency tree       
Reading state information... Done
The following extra packages will be installed:
  libdrm-dev libgl1-mesa-dev libglu1-mesa-dev libpthread-stubs0-dev libx11-dev libx11-xcb-dev libxau-dev
  libxcb-dri2-0-dev libxcb-glx0-dev libxcb1-dev libxdamage-dev libxdmcp-dev libxext-dev libxfixes-dev
  libxxf86vm-dev mesa-common-dev x11proto-damage-dev x11proto-dri2-dev x11proto-fixes-dev x11proto-gl-dev
  x11proto-xf86vidmode-dev
[...]
$ sudo apt-get install cmake git g++ zlib1g-dev libao-dev libgl1-mesa-dev libasound2-dev libcurl4-gnutls-dev libglew-dev libmpg123-dev ninja-build

I tried to compile against this version, but too different "error: ‘GLFWwindow’ does not name a type"
Postpojning further stuff (manually installing deb package) until end of week.

**Comment by sasq64** [comment]
Yes glfw version 2 is not compatible with version 3
