### ISSUE TITLE
Keyboard input assumes qwerty layout

### ISSUE THREAD

**Issue by emoon** [sasq64/chipmachine#36]
If one uses a non-qwerty layout set in Windows the app still assumes that it's always qwerty.

**Comment by sasq64** [comment]
Seems to be caused by this;
https://github.com/glfw/glfw/issues/518

Will try to upgrade glfw for the next release.

**Comment by emoon** [comment]
Sweet! Thanks.

**Comment by sasq64** [comment]
Fixed in 1.3b

**Comment by emoon** [comment]
Thanks :)
