### ISSUE TITLE
Build from Source Fails on amd64 and armhf

### ISSUE THREAD

**Issue by jpyper** [sasq64/chipmachine#39]
I have followed all the directions in the README to build this project. Everything seems to be going just fine until it gets towards the last few parts. The output below is from a ODROID-XU4 (same basic hardware as RasPi2 but think 4 of them together) running Debian sid.

john@xu4:~/src/chipmach/build$ uname -a
Linux xu4 3.10.96+ #1 SMP PREEMPT Sun Feb 14 11:47:29 CET 2016 armv7l GNU/Linux

john@xu4:~/src/chipmach/build$ lsb_release -a
No LSB modules are available.
Distributor ID:	Debian
Description:	Debian GNU/Linux testing-updates (sid)
Release:	testing-updates
Codename:	sid

john@xu4:~/src/chipmach/build$ gcc --version
gcc (Debian 6-20160313-1) 6.0.0 20160313 (experimental) [trunk revision 234167]

john@xu4:~/src/chipmach/build$ ninja --version
1.6.0

john@xu4:~/src/chipmach/build$ cmake --version
cmake version 3.5.1

Below is the error I get (same error on both armhf (xu4) and amd64 (my laptop):

[1253/1278] Building CXX object CMakeFiles/chipmachine.dir/src/ChipMachine.cpp.o
FAILED: /usr/bin/c++   -DAPP_NAME=chipmachine -I/home/john/src/chipmach/chipmachine/../apone/mods -I/usr/local/include -I/home/john/src/chipmach/chipmachine/../apone/mods/grappix -I/home/john/src/chipmach/chipmachine/../apone/mods/musicplayer/plugins -g -funsigned-char -std=c++11  -g -funsigned-char -O2 -MMD -MT CMakeFiles/chipmachine.dir/src/ChipMachine.cpp.o -MF CMakeFiles/chipmachine.dir/src/ChipMachine.cpp.o.d -o CMakeFiles/chipmachine.dir/src/ChipMachine.cpp.o -c /home/john/src/chipmach/chipmachine/src/ChipMachine.cpp
/home/john/src/chipmach/chipmachine/src/ChipMachine.cpp: In member function ‘void chipmachine::ChipMachine::render(uint32_t)’:
/home/john/src/chipmach/chipmachine/src/ChipMachine.cpp:529:28: error: no matching function for call to ‘grappix::BaseList<grappix::VerticalLayout>::render(std::shared_ptr<grappix::Window>&)’
   songList.render(screenptr);
                            ^
In file included from /home/john/src/chipmach/chipmachine/src/ChipMachine.h:30:0,
                 from /home/john/src/chipmach/chipmachine/src/ChipMachine.cpp:1:
/home/john/src/chipmach/chipmachine/../apone/mods/grappix/grappix/gui/list.h:68:7: note: candidate: void grappix::BaseList<LAYOUT>::render(std::shared_ptr<grappix::RenderTarget>, uint32_t) [with LAYOUT = grappix::VerticalLayout; uint32_t = unsigned int]
  void render(std::shared_ptr<RenderTarget> target, uint32_t delta) override {
       ^~~~~~
/home/john/src/chipmach/chipmachine/../apone/mods/grappix/grappix/gui/list.h:68:7: note:   candidate expects 2 arguments, 1 provided
[1253/1278] Building CXX object CMakeFiles/chipmachine.dir/src/MusicDatabase.cpp.o
ninja: build stopped: subcommand failed.
john@xu4:~/src/chipmach/build$

**Comment by zigurana** [comment]
Same here on a Raspberry Pi 3:

Linux retropie 4.1.19-v7+ #858 SMP Tue Mar 15 15:56:00 GMT 2016 armv7l GNU/Linux
gcc (Raspbian 4.9.2-10) 4.9.2
ninja --version : 1.3.4
cmake version 3.0.2


Build output:

> [1251/1279] Building CXX object CMakeFiles/chipmachine.dir/src/ChipMachine.cpp.o
FAILED: /usr/bin/c++   -DAPP_NAME=chipmachine -DGL_ES -DRASPBERRYPI -mfloat-abi=hard -I/opt/vc/include -mfpu=vfp -g -funsigned-char -std=c++11  -DGL_ES -DRASPBERRYPI -mfloat-abi=hard -I/opt/vc/include -mfpu=vfp -g -funsigned-char -O2 -I/home/pi/chipmachine/../apone/mods -I/usr/local/include -I/home/pi/chipmachine/../apone/mods/grappix -I/home/pi/chipmachine/../apone/mods/musicplayer/plugins -MMD -MT CMakeFiles/chipmachine.dir/src/ChipMachine.cpp.o -MF CMakeFiles/chipmachine.dir/src/ChipMachine.cpp.o.d -o CMakeFiles/chipmachine.dir/src/ChipMachine.cpp.o -c /home/pi/chipmachine/src/ChipMachine.cpp
/home/pi/chipmachine/src/ChipMachine.cpp: In member function ‘void chipmachine::ChipMachine::render(uint32_t)’:
/home/pi/chipmachine/src/ChipMachine.cpp:529:28: error: no matching function for call to ‘grappix::BaseList<grappix::VerticalLayout>::render(std::shared_ptr<grappix::Window>&)’
   songList.render(screenptr);
                            ^
/home/pi/chipmachine/src/ChipMachine.cpp:529:28: note: candidate is:
In file included from /home/pi/chipmachine/src/ChipMachine.h:30:0,
                 from /home/pi/chipmachine/src/ChipMachine.cpp:1:
/home/pi/chipmachine/../apone/mods/grappix/grappix/gui/list.h:68:7: note: void grappix::BaseList<LAYOUT>::render(std::shared_ptr<grappix::RenderTarget>, uint32_t) [with LAYOUT = grappix::VerticalLayout; uint32_t = unsigned int]
  void render(std::shared_ptr<RenderTarget> target, uint32_t delta) override {
       ^
/home/pi/chipmachine/../apone/mods/grappix/grappix/gui/list.h:68:7: note:   candidate expects 2 arguments, 1 provided
[1251/1279] Building CXX object CMakeFiles/chipmachine.dir/src/MusicDatabase.cpp.o
ninja: build stopped: subcommand failed.

**Comment by sasq64** [comment]
There was a mismatch between the chipmachine and apone versions.
Should not happen any longer since I have merged dev -> trunk in preparation for 1.3 release
