### ISSUE TITLE
No letters when typing in search query

### ISSUE THREAD

**Issue by Duality4Y** [sasq64/chipmachine#40]
No letter appear onscreen when i type the search querry,
however the list of items that match so far do appear.
http://i.sonck.nl/img/c5

**Comment by sasq64** [comment]
Is this on the same hardware that earlier didn't show any text at all?

**Comment by Duality4Y** [comment]
yes well this is a hardware issue i figured that out because the same compiled program runs fine on another machine. (my graphics card is not supported so yea .. )
