### ISSUE TITLE
Set Window Title when Running ChipMachine Binary

### ISSUE THREAD

**Issue by jpyper** [sasq64/chipmachine#42]
Like the title says, it would be nice to have the application set the window title while it is running. Currently it just says "Untitled". 

If at all possible, have it set the program name and the current team that is playing.

Ex:
ChipMachine - Castlevania - Bloody Tears (NES/FC)

This is just a thought and wishlist thing. If it's not possible or not going to happen, please feel free to close this issue.

**Comment by sasq64** [comment]
This is easy and I will fix it in the next release.

**Comment by sasq64** [comment]
Implemented in 1.3b
