### ISSUE TITLE
Runtime error when starting chipmachine

### ISSUE THREAD

**Issue by FreeFull** [sasq64/chipmachine#47]
With the latest git revisions of chipmachine and apone, when I try to run `./chipmachine` or `./cm`, I get this error:

```
terminate called after throwing an instance of 'std::runtime_error'
  what():  Illegal cast to string; type is actually empty
Aborted (core dumped)
```

The only time I don't get the error is when I run `./chipmachine --help`.
My platform is Linux. Compiled using the instructions from the readme.

**Comment by laama1** [comment]
Same problem here. I'm using Fedora25, and I followed the install instructions from the front page as close as possible.
Compiled twice, no difference. More compiling instructions needed..

**Comment by arboreal84** [comment]
Same problem here

**Comment by sasq64** [comment]
I'm currently trying to find time to release an update, I have fixed in the master now at least, but I need to change command line parsing.

**Comment by sasq64** [comment]
This should be fixed now
