### ISSUE TITLE
Crash when switching to SID files (Windows 10 - 1511 - 10586.633)

### ISSUE THREAD

**Issue by JeremyLC** [sasq64/chipmachine#48]
Windows 10 (V1511, Build 10586.633) After the most recent Windows Updates Chipmachine now crashes, a LOT, when when trying to switch to SID tunes. The fault offset is the same every time. I tried to run with the -d switch, but chipmachine didn't produce any additional debugging output. Exception code 0xc0000005 is a memory access violation, and the offset is the same every time it crashes.

From the Windows Application Log:

Faulting application name: chipmachine.exe, version: 0.0.0.0, time stamp: 0x00000000
Faulting module name: chipmachine.exe, version: 0.0.0.0, time stamp: 0x00000000
Exception code: 0xc0000005
Fault offset: 0x005f20b5
Faulting process id: 0x1220
Faulting application start time: 0x01d22ba188376bee
Faulting application path: C:\Users<username>\Music\chipmachine\chipmachine.exe
Faulting module path: C:\Users<username>\Music\chipmachine\chipmachine.exe
Report Id: 1bb3e449-70eb-4aa7-97ed-b900af860083
Faulting package full name: 
Faulting package-relative application ID: 

From the corresponding WER file

Version=1
EventType=APPCRASH
EventTime=131215312023655582
ReportType=2
Consent=1
UploadTime=131215312025553345
ReportIdentifier=cbe6fc2c-9794-11e6-82cd-c0335eddad86
IntegratorReportIdentifier=1bb3e449-70eb-4aa7-97ed-b900af860083
WOW64=1
NsAppName=chipmachine.exe
Response.type=4
Sig[0].Name=Application Name
Sig[0].Value=chipmachine.exe
Sig[1].Name=Application Version
Sig[1].Value=0.0.0.0
Sig[2].Name=Application Timestamp
Sig[2].Value=00000000
Sig[3].Name=Fault Module Name
Sig[3].Value=chipmachine.exe
Sig[4].Name=Fault Module Version
Sig[4].Value=0.0.0.0
Sig[5].Name=Fault Module Timestamp
Sig[5].Value=00000000
Sig[6].Name=Exception Code
Sig[6].Value=c0000005
Sig[7].Name=Exception Offset
Sig[7].Value=005f20b5
DynamicSig[1].Name=OS Version
DynamicSig[1].Value=10.0.10586.2.0.0.256.48
DynamicSig[2].Name=Locale ID
DynamicSig[2].Value=1033
DynamicSig[22].Name=Additional Information 1
DynamicSig[22].Value=bdcb
DynamicSig[23].Name=Additional Information 2
DynamicSig[23].Value=bdcb33e65a9843796b7ec31cc25bda3b
DynamicSig[24].Name=Additional Information 3
DynamicSig[24].Value=b892
DynamicSig[25].Name=Additional Information 4
DynamicSig[25].Value=b892054ec8a92265ec8b48f9a5510fdf
UI[2]=C:\Users<username>\Music\chipmachine\chipmachine.exe
UI[3]=chipmachine.exe has stopped working
UI[4]=Windows can check online for a solution to the problem.
UI[5]=Check online for a solution and close the program
UI[6]=Check online for a solution later and close the program
UI[7]=Close the program
LoadedModule[0]=C:\Users<username>\Music\chipmachine\chipmachine.exe
LoadedModule[1]=C:\WINDOWS\SYSTEM32\ntdll.dll
LoadedModule[2]=C:\WINDOWS\SYSTEM32\KERNEL32.DLL
LoadedModule[3]=C:\WINDOWS\SYSTEM32\KERNELBASE.dll
LoadedModule[4]=C:\WINDOWS\SYSTEM32\ADVAPI32.dll
LoadedModule[5]=C:\WINDOWS\SYSTEM32\msvcrt.dll
LoadedModule[6]=C:\WINDOWS\SYSTEM32\sechost.dll
LoadedModule[7]=C:\WINDOWS\SYSTEM32\RPCRT4.dll
LoadedModule[8]=C:\WINDOWS\SYSTEM32\SspiCli.dll
LoadedModule[9]=C:\WINDOWS\SYSTEM32\CRYPTBASE.dll
LoadedModule[10]=C:\WINDOWS\SYSTEM32\bcryptPrimitives.dll
LoadedModule[11]=C:\WINDOWS\SYSTEM32\GDI32.dll
LoadedModule[12]=C:\WINDOWS\SYSTEM32\USER32.dll
LoadedModule[13]=C:\WINDOWS\SYSTEM32\SHELL32.dll
LoadedModule[14]=C:\WINDOWS\SYSTEM32\cfgmgr32.dll
LoadedModule[15]=C:\WINDOWS\SYSTEM32\windows.storage.dll
LoadedModule[16]=C:\WINDOWS\SYSTEM32\combase.dll
LoadedModule[17]=C:\WINDOWS\SYSTEM32\shlwapi.dll
LoadedModule[18]=C:\Users<username>\Music\chipmachine\libwinpthread-1.dll
LoadedModule[19]=C:\WINDOWS\SYSTEM32\kernel.appcore.dll
LoadedModule[20]=C:\WINDOWS\SYSTEM32\shcore.dll
LoadedModule[21]=C:\WINDOWS\SYSTEM32\powrprof.dll
LoadedModule[22]=C:\WINDOWS\SYSTEM32\OPENGL32.DLL
LoadedModule[23]=C:\WINDOWS\SYSTEM32\profapi.dll
LoadedModule[24]=C:\WINDOWS\SYSTEM32\WS2_32.dll
LoadedModule[25]=C:\WINDOWS\SYSTEM32\WINMM.DLL
LoadedModule[26]=C:\WINDOWS\SYSTEM32\GLU32.dll
LoadedModule[27]=C:\WINDOWS\SYSTEM32\DDRAW.dll
LoadedModule[28]=C:\Users<username>\Music\chipmachine\libcurl-4.dll
LoadedModule[29]=C:\WINDOWS\SYSTEM32\wldap32.dll
LoadedModule[30]=C:\Users<username>\Music\chipmachine\glew32.dll
LoadedModule[31]=C:\Users<username>\Music\chipmachine\libmpg123-0.dll
LoadedModule[32]=C:\Users<username>\Music\chipmachine\zlib1.dll
LoadedModule[33]=C:\Users<username>\Music\chipmachine\libgcc_s_dw2-1.dll
LoadedModule[34]=C:\Users<username>\Music\chipmachine\libstdc++-6.dll
LoadedModule[35]=C:\WINDOWS\SYSTEM32\WINMMBASE.dll
LoadedModule[36]=C:\WINDOWS\SYSTEM32\DCIMAN32.dll
LoadedModule[37]=C:\Users<username>\Music\chipmachine\LIBEAY32.dll
LoadedModule[38]=C:\Users<username>\Music\chipmachine\libidn-11.dll
LoadedModule[39]=C:\Users<username>\Music\chipmachine\libnghttp2-14.dll
LoadedModule[40]=C:\Users<username>\Music\chipmachine\librtmp-1.dll
LoadedModule[41]=C:\Users<username>\Music\chipmachine\libssh2-1.dll
LoadedModule[42]=C:\Users<username>\Music\chipmachine\SSLEAY32.dll
LoadedModule[43]=C:\Users<username>\Music\chipmachine\libiconv-2.dll
LoadedModule[44]=C:\Users<username>\Music\chipmachine\libintl-8.dll
LoadedModule[45]=C:\Users<username>\Music\chipmachine\libgmp-10.dll
LoadedModule[46]=C:\Users<username>\Music\chipmachine\libgnutls-30.dll
LoadedModule[47]=C:\Users<username>\Music\chipmachine\libhogweed-4-1.dll
LoadedModule[48]=C:\Users<username>\Music\chipmachine\libnettle-6-1.dll
LoadedModule[49]=C:\WINDOWS\SYSTEM32\CRYPT32.dll
LoadedModule[50]=C:\WINDOWS\SYSTEM32\MSASN1.dll
LoadedModule[51]=C:\Users<username>\Music\chipmachine\libtasn1-6.dll
LoadedModule[52]=C:\Users<username>\Music\chipmachine\libp11-kit-0.dll
LoadedModule[53]=C:\Users<username>\Music\chipmachine\libffi-6.dll
LoadedModule[54]=C:\WINDOWS\SYSTEM32\IMM32.DLL
LoadedModule[55]=C:\WINDOWS\SYSTEM32\ncrypt.dll
LoadedModule[56]=C:\WINDOWS\SYSTEM32\bcrypt.dll
LoadedModule[57]=C:\WINDOWS\SYSTEM32\NTASN1.dll
LoadedModule[58]=C:\WINDOWS\SYSTEM32\CRYPTSP.dll
LoadedModule[59]=C:\WINDOWS\system32\rsaenh.dll
LoadedModule[60]=C:\WINDOWS\system32\uxtheme.dll
LoadedModule[61]=C:\WINDOWS\SYSTEM32\dinput8.dll
LoadedModule[62]=C:\WINDOWS\SYSTEM32\xinput1_4.dll
LoadedModule[63]=C:\WINDOWS\SYSTEM32\DEVOBJ.dll
LoadedModule[64]=C:\WINDOWS\SYSTEM32\dwmapi.dll
LoadedModule[65]=C:\Program Files (x86)\Common Files\Microsoft Shared\Ink\tiptsf.dll
LoadedModule[66]=C:\WINDOWS\SYSTEM32\OLEAUT32.dll
LoadedModule[67]=C:\WINDOWS\SYSTEM32\HID.DLL
LoadedModule[68]=C:\WINDOWS\SYSTEM32\SETUPAPI.DLL
LoadedModule[69]=C:\WINDOWS\SYSTEM32\WINTRUST.dll
LoadedModule[70]=C:\WINDOWS\SYSTEM32\MSCTF.dll
LoadedModule[71]=C:\WINDOWS\SYSTEM32\ig75icd32.dll
LoadedModule[72]=C:\WINDOWS\SYSTEM32\WTSAPI32.dll
LoadedModule[73]=C:\WINDOWS\SYSTEM32\igdusc32.dll
LoadedModule[74]=C:\WINDOWS\SYSTEM32\clbcatq.dll
LoadedModule[75]=C:\Windows\SYSTEM32\uiautomationcore.dll
LoadedModule[76]=C:\Windows\SYSTEM32\USERENV.dll
LoadedModule[77]=C:\WINDOWS\SYSTEM32\sxs.dll
LoadedModule[78]=C:\Windows\SYSTEM32\OLEACC.dll
LoadedModule[79]=C:\WINDOWS\SYSTEM32\MMDevAPI.DLL
LoadedModule[80]=C:\WINDOWS\SYSTEM32\PROPSYS.dll
LoadedModule[81]=C:\WINDOWS\SYSTEM32\wdmaud.drv
LoadedModule[82]=C:\WINDOWS\SYSTEM32\AVRT.dll
LoadedModule[83]=C:\WINDOWS\SYSTEM32\ksuser.dll
LoadedModule[84]=C:\WINDOWS\SYSTEM32\secur32.dll
LoadedModule[85]=C:\WINDOWS\SYSTEM32\AUDIOSES.DLL
LoadedModule[86]=C:\WINDOWS\SYSTEM32\wintypes.dll
LoadedModule[87]=C:\WINDOWS\SYSTEM32\msacm32.drv
LoadedModule[88]=C:\WINDOWS\SYSTEM32\MSACM32.dll
LoadedModule[89]=C:\WINDOWS\SYSTEM32\midimap.dll
LoadedModule[90]=C:\WINDOWS\SYSTEM32\ole32.dll
LoadedModule[91]=C:\WINDOWS\system32\mswsock.dll
LoadedModule[92]=C:\WINDOWS\SYSTEM32\DNSAPI.dll
LoadedModule[93]=C:\WINDOWS\SYSTEM32\NSI.dll
LoadedModule[94]=C:\Windows\System32\rasadhlp.dll
LoadedModule[95]=C:\WINDOWS\SYSTEM32\IPHLPAPI.DLL
LoadedModule[96]=C:\WINDOWS\System32\fwpuclnt.dll
FriendlyEventName=Stopped working
ConsentKey=APPCRASH
AppName=chipmachine.exe
AppPath=C:\Users<username>\Music\chipmachine\chipmachine.exe
NsPartner=windows
NsGroup=windows8
ApplicationIdentity=F080A44C78911C114B1D18F2E4816B7D

**Comment by JeremyLC** [comment]
Looks like something changed on the HVSC host. Whenever Chipmachine tries to retrieve a SID file it gets an "ERROR: File path does not exist" and a directory listing instead of a valid SID file. I've attached a sample of what should've been a SID file, but instead came back as an error.

This is the URL Chipmachine tried to fetch that did not work.
http://www.sannic.nl/hvsc/HVSC63/C64Music/MUSICIANS/T/Tel_Jeroen/Fun_Fun.sid

**Comment by JeremyLC** [comment]
It looks like sannic.nl has changed to reuire httpS, but instead of redirecting they give an error page. So,

this fails (and does NOT return an HTTP 404, which is ANOTHER misconfiguration on their part)
http://www.sannic.nl/hvsc/HVSC63/C64Music/MUSICIANS/T/Tel_Jeroen/Fun_Fun.sid

and this works
https://www.sannic.nl/hvsc/HVSC63/C64Music/MUSICIANS/T/Tel_Jeroen/Fun_Fun.sid

This exposes a minor bug in Chipmachine in that it doesn't verify that it actually has a legitimate SID file before it tries to load and play it. The SID playback engine crashes trying to load the HTML error page that it thinks is a SID file.

**Comment by sasq64** [comment]
Just changing the source in `lua/db.lua` to
`source = "https://www.sannic.nl/hvsc/C64Music/"`
seems to work for now.
