### ISSUE TITLE
Compiling instruction mistake

### ISSUE THREAD

**Issue by HybridDog** [sasq64/chipmachine#51]
`cmake ../chipmachine -GNinja -DCMAKE_BUILD_TYPE=Release` 
should be 
`cmake ../ -GNinja -DCMAKE_BUILD_TYPE=Release`

**Comment by dobbymoodge** [comment]
@HybridDog you misread the instructions. You probably did `cd chipmachine` after cloning the repo. The `README` is expecting you check out the `apone` and `musicplayer` repos into sibling directories and then `mkdir build` at the same level, so you wind up with a directory structure like this:

```
# ls -l
drwxrwxr-x. 14 user group  4096 Jan  2 12:00 build
drwxrwxr-x. 14 user group  4096 Jan  2 12:00 apone
drwxrwxr-x. 12 user group  4096 Jan  2 12:00 chipmachine
drwxrwxr-x.  7 user group  4096 Jan  2 12:00 musicplayer
```

Running builds from a sibling directory isn't exactly uncommon, though it is a little obscure. It lets you avoid crapping up the project directory with all the intermediate and final build artifacts, as long as the project is set up properly.

**Comment by dobbymoodge** [comment]
@sasq64 you should probably close this :)

**Comment by HybridDog** [comment]
I opened the issue before https://github.com/sasq64/chipmachine/commit/bdff5c6821f7d8e6e299a367601279d54cfbe697#diff-04c6e90faac2675aa89e2176d2eec7d8.
When I followed those instructions, the build folder was in the chipmachine folder.
