### ISSUE TITLE
Make git submodule to compatible version of apone

### ISSUE THREAD

**Issue by arboreal84** [sasq64/chipmachine#55]
The latest apone breaks compatibility with chipmachine.
So it would be good to have chipmachine consume the apone dependency as a submodule to ensure compatibility across versions.

**Comment by rheasman** [comment]
Can anyone tell me what version I should be using then? I'm getting a compile error and am not sure if it is related.

`
/home/ray/build/chipmachine/chipmachine/src/GZPlugin.h:7:25: error: ‘musix’ has not been declared
 class GZPlugin : public musix::ChipPlugin {
`

**Comment by arboreal84** [comment]
I have a really old version, but works.
apone @ d320e07159a35f47cbc81ea45f145c27a976f98c
chipmachine @ bee2cc8ede5eb13da6c11f4f75d7d3cdb662a9a6

**Comment by rheasman** [comment]
Thanks!

**Comment by sasq64** [comment]
I had apone as a submodule for a while but it is problematic for me since I use it in other projets too. Instead I tried to make a corresponding tag in apone when I made a chipmachine release. I missed it for 1.3, but there is one for 1.4 beta.

Of course if you just get the latest code it _should_ work. Recently I extracted the musicplayer system from apone into it's own repo and you need to checkout all three repos in the same directory to build, but I updated the Chipmachine README to reflect that.

**Comment by rheasman** [comment]
I'm sorry to say that it doesn't. On my Linux system, cloning everything out into a common directory, creating a build directory, running cmake as per the docs inside the directory, and then running ninja fails with the above namespace error.

Rewinding the chipmachine clone back past commit b12f09fcf39cf79a7230f134a816bb1645eb8768 ("namespace rename + small fixes") then generates a cmake error.

After spending an hour trying to find a working combination of commit versions from the three repos that would work together, I gave up. I just wanted to listen to one song. :-)

**Comment by arboreal84** [comment]
@sasq64, I tried building the following combination:
- chipmachine @ b12f09fcf39cf79a7230f134a816bb1645eb8768
- apone @ ea3db26b3486e29cef94df327a328895983f2bdc
- musicplayer @ d0c871d1a51ce9af75740bc385afb5a89b2bb44e
and obtained a bunch of compile time errors.

e.g:
```c++
chipmachine/src/MusicPlayer.h:79:31: error: ‘ChipPlayer’ is not a member of ‘chipmachine’
  std::shared_ptr<chipmachine::ChipPlayer> fromFile(const std::string &fileName);
                               ^~~~~~~~~~
```

**Comment by sasq64** [comment]
Seems I had not pushed the latest changed to _apone_. Could you try again now?

**Comment by sasq64** [comment]
And as mentioned, this should also work
```
cd chipmachine
git checkout v1.4b3
cd apone
git checkout chipmachine-v1.4b3
cd ..
./build.py
```

**Comment by arboreal84** [comment]
It does work now, @sasq64.
Thanks for following up.

Just for the record, the combination of working versions are:
apone @ a805779ac2532ad5fe326e73a05b59f198572e9d
chipmachine @ b12f09fcf39cf79a7230f134a816bb1645eb8768
musicplayer @ d0c871d1a51ce9af75740bc385afb5a89b2bb44e
