### ISSUE TITLE
Backspace not working in search screen

### ISSUE THREAD

**Issue by ghost** [sasq64/chipmachine#56]
Hi, first thank you for this nice program!

I've build chipmachine from the latest git revision. In the search screen `backspace` does not work.
Also the used keymap seems to be wrong. I have a german keyboard layout and `z`, `y` are swapped.

With v1.4b3 it worked, seems it was introduced with the keycode namespace changes.

**Comment by sasq64** [comment]
Should be fixed now (pull new apone)

**Comment by mstraube** [comment]
Tried with latest apone but it's still not working.

**Comment by sasq64** [comment]
Duh, there was a small change to chipmachine itself too that I forgot to push. Try now.

**Comment by sasq64** [comment]
Well the z,y thing is probably not fixed. That's a slightly more complicated fix...

**Comment by mstraube** [comment]
Backspace works now, thank you. Z,y are still swapped, as you say...
