### ISSUE TITLE
Not loading anything?

### ISSUE THREAD

**Issue by farazfp** [sasq64/chipmachine#58]
Hi there, LOVE chipmachine, but since around a month ago, it isn't able to load any tracks at all. Cached files are fine, but those which are no longer/were never cached just don't load and the "Can't play "
error shows after an uncharacteristically long period, if ever. The loading icon is displayed up in the left corner and just stays there.

**Comment by sasq64** [comment]
I think this was due to the fact that modland stopped supporting http. I changed it to using ftp and it seems to work.

**Comment by farazfp** [comment]
The http interface seems to be back. I added "http://modland.com/pub/modules/" as the Modland source, deleted music.db, and it works now. Thanks, and keep rocking! :)
